meta:
- desc: |
   install ceph/squid v19.2.2
tasks:
- install:
    # When this ceph version is changed, make sure to fix the testcase
    # 'test_multifs_single_client_cross_access_r_caps_end' in
    # qa/tasks/cephfs/test_admin.py
    tag: v19.2.2
- print: "**** done installing squid v19.2.2"
- ceph:
    log-ignorelist:
      - overall HEALTH_
      - \(FS_
      - \(MDS_
      - \(OSD_
      - \(MON_DOWN\)
      - \(CACHE_POOL_
      - \(POOL_
      - \(MGR_DOWN\)
      - \(PG_
      - \(SMALLER_PGP_NUM\)
      - Monitor daemon marked osd
      - Behind on trimming
      - Manager daemon
    conf:
      global:
        mon warn on pool no app: false
- exec:
    mon.a:
    - ceph osd dump -f json-pretty
    - ceph versions
    - ceph fs status
    - ceph health detail
- print: "**** done ceph"
